---
title: Créer un PNJ à partir de formes 3D
hero_image: images/banner.png
description: Créer un PNJ à partir de formes 3D
version: 4
listed: false
copyedit: false
last_tested: "2021-11-24"
steps:
  - title: Créer un PNJ à partir de formes 3D
